# Generated by Django 4.1.1 on 2023-01-04 14:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variant_remove_product_barcode_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=None, null=True, size=None)),
                ('position', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'variant_option',
            },
        ),
        migrations.AddConstraint(
            model_name='variantoption',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_variant_option_name'),
        ),
    ]
