# Generated by Django 4.1.1 on 2023-01-02 01:04

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_image', models.FileField(blank=True, max_length=1024, null=True, upload_to=core.models.UploadTo('shops', 'customer_feedback'))),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'landing_page_feedback',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.FileField(blank=True, max_length=1024, null=True, upload_to=core.models.UploadTo('shops', 'images'))),
                ('type', models.CharField(choices=[('BANNER', 'BANNER'), ('WORKSPACE', 'WORKSPACE')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'landing_page_image',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'landing_page_time_setting',
                'ordering': ['created_at'],
            },
        ),
    ]
