# Generated by Django 4.1.1 on 2023-01-02 01:04

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('ascii_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='UNKNOWN', max_length=10)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('day_of_birth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_of_birth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_of_birth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avatar_url', models.FileField(blank=True, max_length=1024, null=True, upload_to=core.models.UploadTo('shops', 'customer'))),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('branches', models.ManyToManyField(blank=True, null=True, related_name='branches', to='shops.branch')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_customer_phone'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_customer_code'),
        ),
    ]
