version: '3'
services:
  app:
    build: .
    environment:
      DATABASE_NAME: spago
      DATABASE_USER: dev
      DATABASE_PASSWORD: secret
      DATABASE_HOST: db
      CREDENTIAL_PATH: /tmp/service_account.json
    volumes:
      - .:/code
    ports:
      - "8000:80"

