# Generated by Django 4.1.1 on 2023-01-02 01:04

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug_name', models.SlugField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('root_branch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'branch',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug_name', models.SlugField(blank=True, max_length=100, null=True)),
                ('slug_name_index', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dayoff_allowed', models.PositiveIntegerField(blank=True, default=2, null=True)),
                ('hotline', models.CharField(blank=True, max_length=15, null=True)),
                ('logo_url', models.FileField(blank=True, max_length=1024, null=True, upload_to=core.models.UploadTo('shops', 'logo'))),
                ('copyright', models.TextField(blank=True, null=True)),
                ('owner_info', models.TextField(blank=True, null=True)),
                ('landing_page_title', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='shops.branch')),
            ],
            options={
                'db_table': 'printers',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(fields=('ip', 'branch'), name='unique_ip_branch'),
        ),
    ]
