# Generated by Django 4.1.1 on 2023-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('user_id', models.UUIDField()),
            ],
            options={
                'db_table': 'active_code',
            },
        ),
    ]
