# Generated by Django 4.1.1 on 2022-10-27 19:56

from django.db import migrations, models
from apps.users.models import RoleName


def migrate_notification_category(apps, schema_editor):
    NotificationCategory = apps.get_model("notifications", "NotificationCategory")
    NotificationSetting = apps.get_model("notifications", "NotificationSetting")
    User = apps.get_model("users", "User")
    categories = NotificationCategory.objects.all()
    settings = []
    for category in categories:
        users = (
            User.objects.filter(~models.Q(role__name=RoleName.CUSTOMER.value))
            .exclude(
                id__in=User.objects.filter(
                    notificationsetting__category=category,
                ).values_list("id", flat=True)
            )
            .values("id")
        )
        for user in users:
            settings.append(
                NotificationSetting(
                    user_id=user["id"], category=category
                )
            )
    NotificationSetting.objects.bulk_create(settings)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_init_notification_category_data"),
    ]

    operations = [
        migrations.RunPython(migrate_notification_category),
    ]
